### ISSUE TITLE
Bug on infite scroll category 

### ISSUE THREAD

**Issue by Lovethydemon** [Sage-Goddess/sagegoddess-ionic#33]
<img width="843" alt="Screenshot 2023-12-11 at 10 55 56 AM" src="https://github.com/Sage-Goddess/sagegoddess-ionic/assets/92010350/1b7004ec-adcb-433e-bb03-d14634334b68">

**Comment by Ruo2023** [comment]
![Screenshot 2023-12-11 at 4 33 44 PM](https://github.com/Sage-Goddess/sagegoddess-ionic/assets/135056315/c1ef209b-6d56-46af-8f02-4a57c270b556)


Added a  pageInfo {
      hasNextPage
    } for collectionpage, but it will return false at current collectionpage, categoryId: 7514 for testing.
